version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: echo "Staring tests"
      - run: mvn clean test
      - run: echo "Test completed"
      - run: mvn clean package
      - run: echo "Artifacts created"
